[package]
name = "fanuc_ucl"
version = "1.6.1"
edition = "2024"
license = "Apache-2.0"
authors = ["Bowan Foryt <bowan@valstad.com>"]
description = "Unofficial Control Library for FANUC Robots"
repository = "https://github.com/valstad-shipworks/fanuc_ucl"
documentation = "https://docs.rs/fanuc_ucl"
readme = "README.md"
keywords = ["python", "robotics", "fanuc"]
categories = ["science::robotics", "hardware-support", "network-programming"]
exclude = ["examples/showcase.gif", "examples/showcase.mp4"]


[lib]
name = "fanuc_ucl"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.29", optional = true, features = ["multiple-pymethods"] }
serde = { version = "1.0", features = ["alloc", "derive", "std"] }
flume = { version = "0.12", features = [], default-features = false }
mio = { version = "1.1.1", features = ["os-poll", "os-ext", "net"] }
thiserror = { version = "2.0" }
cfg_mixin = { version = "0.1.0" }
int-enum = { version = "1.1.2", optional = true }
bitflags = { version = "2.9.4", optional = true }
libc = { version = "0.2", optional = true }
spin_sleep = { version = "1.3.3", optional = true }
monostate = { version = "1.0.1", optional = true }
inventory = { version = "0.3.21", optional = true }
serde_repr = { version = "0.1.20", optional = true }
paste = { version = "1.0.15", optional = true }
serde_json = { version = "1.0.*", optional = true, features = [
    "preserve_order",
] }
event-listener = { version = "5.4.2", optional = true, features = ["std"] }
bincode = { version = "2.0.1", optional = true }
impls = { version = "1.0.3", optional = true }
inherent = { version = "1.0.13", optional = true }
openport = { version = "0.1.1", optional = true }
parking_lot = "0.12.5"
snare = { version = "1.4.1", features = ["mio-compat"] }
cfg-vis = "0.3.0"
atomic-waker = "1.1.2"
valuable = { version = "0.1.1", features = ["derive"], optional = true }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", optional = true }

[dev-dependencies]
snare = { version = "1.4.1", features = ["shim", "mio-compat"] }

[target.'cfg(windows)'.dependencies]
pyo3 = { version = "0.29", optional = true, features = ["extension-module", "auto-initialize", "multiple-pymethods", "generate-import-lib"] }


[features]
default = ["stmo", "rmi", "hspo", "hmi"]
async = ["flume/async"]
stmo = ["joint_conv", "bincode", "spin_sleep", "libc", "bitflags", "openport", "event-listener"]
rmi = [
    "joint_conv",
    "serde_json",
    "serde_repr",
    "monostate",
    "inventory",
    "int-enum",
    "libc",
    "event-listener",
    "inherent",
]
hspo = ["joint_conv", "bincode", "libc"]
hmi = [
    "joint_conv",
    "bincode",
    "int-enum",
    "libc",
    "bitflags",
    "impls",
    "inherent",
]
joint_conv = ["paste"]
py = ["pyo3", "stmo", "rmi", "hspo", "hmi", "serde_json", "dep:tracing-subscriber"]
pyo3 = ["dep:pyo3"]
abi3 = ["py", "pyo3/abi3-py310"]
abi3t = ["py", "pyo3/abi3t-py315"]
valuable = ["dep:valuable"]


[profile.release]
lto = true

[profile.python]
inherits = "release"
debug = "full"
