name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - aarch64-apple-darwin
          - x86_64-pc-windows-msvc

    runs-on: ubuntu-latest
    name: ${{ matrix.target }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Cargo check
        run: cargo check --target ${{ matrix.target }}

      - name: Clippy
        run: cargo clippy --target ${{ matrix.target }} -- -D warnings
